production:
   auto_create: true
   deny_delete: true
   svn:
     path: /var/opt/alminium/svn
     svnadmin: /usr/bin/svnadmin
     url: svn
   git:
     path: /var/opt/alminium/git
     git: /usr/bin/git
     options: 
        - --bare 
        - --template 
        - /opt/alminium/hooks/git
     url: http://git.myhost.com