production:
   auto_create: true
   deny_delete: true
   svn:
     path: /var/opt/alminium/svn
     svnadmin: /usr/bin/svnadmin
     url: http://ホスト名/svn
   git:
     path: /var/opt/alminium/git
     git: /usr/bin/git
     options: 
        - --bare 
        - --template 
        - /opt/alminium/hooks/git
     url: http://ホスト名/git
   mercurial:
     path: /var/opt/alminium/hg
     hg: /usr/bin/hg
     url: http://ホスト名/hg

